---
- name: Launch and setup Multipass VMs on a VirtualBox host-only network
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch VMs with Multipass
      shell: |
        multipass launch --name {{ item.name }} --cpus {{ item.cpus }} --mem {{ item.memory }}G --disk {{ item.disk }}G
      loop:
        - { name: 'mosip-db', cpus: '2', memory: '4', disk: '50' }
        - { name: 'mosip-mq', cpus: '2', memory: '2', disk: '20' }
        - { name: 'mosip-workflow', cpus: '2', memory: '2', disk: '20' }
        - { name: 'mosip-core', cpus: '4', memory: '8', disk: '50' }
        - { name: 'mosip-ui', cpus: '2', memory: '4', disk: '20' }
        - { name: 'mosip-auth', cpus: '2', memory: '2', disk: '20' }
